import { PokemonProvider } from '@/context/PokemonContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PokedexProvider } from '@/context/PokedexContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 sm:pt-36 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90 -z-10`}>
        <PokedexProvider>
          <PokemonProvider>
            {children}
          </PokemonProvider>
        </PokedexProvider>
      </body>
    </html>
  )
}
