import { PokemonProvider } from '@/context/PokemonContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PokedexProvider, usePokedex } from '@/context/PokedexContext'
import SupabaseProvider from '@/providers/SupabaseProvider'
import UserProvider from '@/providers/UserProvider'
import ModalProvider from '@/providers/ModalProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-b from-gray-100 to-gray-200 text-gray-950 relative dark:bg-gradient-to-b dark:from-gray-900 dark:to-gray-600 dark:text-gray-50 dark:text-opacity-90 -z-10`}>
      <SupabaseProvider>
      <UserProvider>
        <PokedexProvider>
                <ModalProvider/>
                  {children}
          </PokedexProvider>
        </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
